In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split()
from sklearn.preprocessing import StandardScaler,LabelEncoder
le = LabelEncoder()
ss = StandardScaler()
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
data = pd.read_csv("C:/Users/HP/OneDrive/Desktop/DataAnalysisFiles/Datasets/breast_disease_data.csv")
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [3]:
data["diagnosis"]=le.fit_transform(data["diagnosis"])
data.head()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302          1        17.99         10.38          122.80     1001.0   
1    842517          1        20.57         17.77          132.90     1326.0   
2  84300903          1        19.69         21.25          130.00     1203.0   
3  84348301          1        11.42         20.38           77.58      386.1   
4  84358402          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [4]:
X = data.iloc[:,2:]
y = data.iloc[:,1]

In [7]:
X.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [24]:
#Train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardization

In [25]:
#Feature Scaing - standardization
X_train = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)
X_train

array([[-0.12348985, -0.29680142, -0.17050713, ..., -0.84082156,
        -0.8563616 , -0.76574773],
       [-0.22826757, -0.65795149, -0.25377521, ..., -0.37706655,
        -1.3415819 , -0.41480748],
       [ 0.14553402, -1.23056444,  0.24583328, ..., -0.04762652,
        -0.08997059,  0.4882635 ],
       ...,
       [ 0.03226081, -0.55578404, -0.08064356, ..., -1.26179013,
        -0.6828391 , -1.27672587],
       [-0.05552593,  0.10949242, -0.04684166, ...,  1.07924018,
         0.4755842 ,  1.25530227],
       [-0.56525537,  0.32333128, -0.619825  , ..., -0.61952313,
        -0.30366032, -0.84348042]])

In [26]:
# LogisticRegession
log = LogisticRegression()
log.fit(X_train,y_train)
log_pred = log.predict(X_test)

accuracy_score(y_test,log_pred)

0.9766081871345029

In [28]:
pd.crosstab(y_test,log_pred)

col_0        0   1
diagnosis         
0          107   1
1            3  60

In [29]:
confusion_matrix(y_test,log_pred)

array([[107,   1],
       [  3,  60]], dtype=int64)

In [31]:
log_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [33]:
log.predict_proba(X_test)

array([[9.05007964e-01, 9.49920362e-02],
       [1.16748950e-05, 9.99988325e-01],
       [5.02257396e-03, 9.94977426e-01],
       [9.99617927e-01, 3.82072740e-04],
       [9.99925116e-01, 7.48843369e-05],
       [4.96048091e-10, 1.00000000e+00],
       [3.03580383e-09, 9.99999997e-01],
       [3.81637707e-02, 9.61836229e-01],
       [7.43623272e-01, 2.56376728e-01],
       [9.99529189e-01, 4.70811112e-04],
       [9.69422152e-01, 3.05778483e-02],
       [1.26726097e-02, 9.87327390e-01],
       [9.95539265e-01, 4.46073514e-03],
       [1.68124082e-01, 8.31875918e-01],
       [9.98774178e-01, 1.22582223e-03],
       [1.90482437e-03, 9.98095176e-01],
       [9.98287690e-01, 1.71231028e-03],
       [9.99988552e-01, 1.14477757e-05],
       [9.99999194e-01, 8.05726183e-07],
       [2.03686825e-06, 9.99997963e-01],
       [9.55198137e-01, 4.48018634e-02],
       [9.91011780e-01, 8.98821980e-03],
       [1.74014262e-08, 9.99999983e-01],
       [9.99945046e-01, 5.49535297e-05],
       [9.989279

In [41]:
log.predict_proba(X_test)[:,1][:10]

array([9.49920362e-02, 9.99988325e-01, 9.94977426e-01, 3.82072740e-04,
       7.48843369e-05, 1.00000000e+00, 9.99999997e-01, 9.61836229e-01,
       2.56376728e-01, 4.70811112e-04])

In [38]:
log_pred[:10]

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0])

In [84]:
np.round(log.predict_proba(X_test),3)[:10]

array([[0.905, 0.095],
       [0.   , 1.   ],
       [0.005, 0.995],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [0.   , 1.   ],
       [0.   , 1.   ],
       [0.038, 0.962],
       [0.744, 0.256],
       [1.   , 0.   ]])

In [82]:
threshold = 0.645
new_pred = np.where(log.predict_proba(X_test)[:,0]>= threshold, 0, 1  )
print(accuracy_score(y_test,new_pred))
confusion_matrix(y_test,new_pred)

0.9883040935672515


array([[107,   1],
       [  1,  62]], dtype=int64)

# Getting the accuracy and confusion matrix for different threshold

In [74]:
# Define the Threshold Function
def predict_threshold(model,X_test,threshold):
    return np.where(np.round(model.predict_proba(X_test)[:,0],3)>= threshold, 0,1)

In [75]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [80]:
for i in np.arange(0,1,0.1):
    y_pred = predict_threshold(log,X_test,i)
    print("Threshold value:",i)
    print("Accuracy Score",accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred),"\n")
    print()

Threshold value: 0.0
Accuracy Score 0.631578947368421
[[108   0]
 [ 63   0]] 


Threshold value: 0.1
Accuracy Score 0.9532163742690059
[[108   0]
 [  8  55]] 


Threshold value: 0.2
Accuracy Score 0.9766081871345029
[[108   0]
 [  4  59]] 


Threshold value: 0.30000000000000004
Accuracy Score 0.9766081871345029
[[108   0]
 [  4  59]] 


Threshold value: 0.4
Accuracy Score 0.9824561403508771
[[108   0]
 [  3  60]] 


Threshold value: 0.5
Accuracy Score 0.9766081871345029
[[107   1]
 [  3  60]] 


Threshold value: 0.6000000000000001
Accuracy Score 0.9883040935672515
[[107   1]
 [  1  62]] 


Threshold value: 0.7000000000000001
Accuracy Score 0.9824561403508771
[[106   2]
 [  1  62]] 


Threshold value: 0.8
Accuracy Score 0.9590643274853801
[[102   6]
 [  1  62]] 


Threshold value: 0.9
Accuracy Score 0.9473684210526315
[[100   8]
 [  1  62]] 




# Bank Churners data

In [85]:
bank = pd.read_csv("C:/Users/HP/OneDrive/Desktop/DataAnalysisFiles/Datasets/BankChurners.csv")
bank.head()

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0  768805383  Existing Customer            45      M                3   
1  818770008  Existing Customer            49      F                5   
2  713982108  Existing Customer            51      M                3   
3  769911858  Existing Customer            40      F                4   
4  709106358  Existing Customer            40      M                3   

  Education_Level Marital_Status Income_Category Card_Category  \
0     High School        Married     $60K - $80K          Blue   
1        Graduate         Single  Less than $40K          Blue   
2        Graduate        Married    $80K - $120K          Blue   
3     High School        Unknown  Less than $40K          Blue   
4      Uneducated        Married     $60K - $80K          Blue   

   Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0              39                         5                       1   
1              44                         6                       1   
2              36                         4                       1   
3              34                         3                       4   
4              21                         5                       1   

   Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0                      3       12691.0                  777          11914.0   
1                      2        8256.0                  864           7392.0   
2                      0        3418.0                    0           3418.0   
3                      1        3313.0                 2517            796.0   
4                      0        4716.0                    0           4716.0   

   Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  
0                 1.335             1144              42                1.625  
1                 1.541             1291              33                3.714  
2                 2.594             1887              20                2.333  
3                 1.405             1171              20                2.333  
4                 2.175              816              28                2.500

In [86]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   CLIENTNUM                 10127 non-null  int64  
 1   Attrition_Flag            10127 non-null  object 
 2   Customer_Age              10127 non-null  int64  
 3   Gender                    10127 non-null  object 
 4   Dependent_count           10127 non-null  int64  
 5   Education_Level           10127 non-null  object 
 6   Marital_Status            10127 non-null  object 
 7   Income_Category           10127 non-null  object 
 8   Card_Category             10127 non-null  object 
 9   Months_on_book            10127 non-null  int64  
 10  Total_Relationship_Count  10127 non-null  int64  
 11  Months_Inactive_12_mon    10127 non-null  int64  
 12  Contacts_Count_12_mon     10127 non-null  int64  
 13  Credit_Limit              10127 non-null  float64
 14  Total_

In [87]:
# Label Enc0ding
x = ["Attrition_Flag","Gender","Education_Level","Marital_Status","Income_Category","Card_Category"]
for i in range(len(x)):
    bank[x[i]]= le.fit_transform(bank[x[i]])

In [88]:
bank.head()

CLIENTNUM  Attrition_Flag  Customer_Age  Gender  Dependent_count  \
0  768805383               1            45       1                3   
1  818770008               1            49       0                5   
2  713982108               1            51       1                3   
3  769911858               1            40       0                4   
4  709106358               1            40       1                3   

   Education_Level  Marital_Status  Income_Category  Card_Category  \
0                3               1                2              0   
1                2               2                4              0   
2                2               1                3              0   
3                3               3                4              0   
4                5               1                2              0   

   Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0              39                         5                       1   
1              44                         6                       1   
2              36                         4                       1   
3              34                         3                       4   
4              21                         5                       1   

   Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0                      3       12691.0                  777          11914.0   
1                      2        8256.0                  864           7392.0   
2                      0        3418.0                    0           3418.0   
3                      1        3313.0                 2517            796.0   
4                      0        4716.0                    0           4716.0   

   Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  
0                 1.335             1144              42                1.625  
1                 1.541             1291              33                3.714  
2                 2.594             1887              20                2.333  
3                 1.405             1171              20                2.333  
4                 2.175              816              28                2.500

In [153]:
X = bank.iloc[:,2:]
y = bank.iloc[:,1]

In [154]:
X.head()

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
0            45       1                3                3               1   
1            49       0                5                2               2   
2            51       1                3                2               1   
3            40       0                4                3               3   
4            40       1                3                5               1   

   Income_Category  Card_Category  Months_on_book  Total_Relationship_Count  \
0                2              0              39                         5   
1                4              0              44                         6   
2                3              0              36                         4   
3                4              0              34                         3   
4                2              0              21                         5   

   Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
0                       1                      3       12691.0   
1                       1                      2        8256.0   
2                       1                      0        3418.0   
3                       4                      1        3313.0   
4                       1                      0        4716.0   

   Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0                  777          11914.0                 1.335   
1                  864           7392.0                 1.541   
2                    0           3418.0                 2.594   
3                 2517            796.0                 1.405   
4                    0           4716.0                 2.175   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  
0             1144              42                1.625  
1             1291              33                3.714  
2             1887              20                2.333  
3             1171              20                2.333  
4              816              28                2.500

In [177]:
#Train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Feature scaling

In [178]:
#Standardization
X_train = ss.fit_transform(X_train)
X_test = ss.fit_transform(X_test)

In [179]:
X_train = pd.DataFrame(X_train,columns = X.columns)
X_test = pd.DataFrame(X_test,columns = X.columns)

# LogisticRegression

In [180]:
log = LogisticRegression()
log.fit(X_train,y_train)
y_preds = log.predict(X_test)
accuracy_score(y_test,y_preds)



0.8996380388285621

In [181]:
pd.crosstab(y_test,y_preds)

col_0             0     1
Attrition_Flag           
0               267   229
1                76  2467

In [182]:
log.coef_

array([[-0.06148612,  0.33017203, -0.14381157, -0.0570637 , -0.12995455,
        -0.02581324, -0.02160704,  0.10939992,  0.68519054, -0.52292106,
        -0.57715464,  0.02321384,  0.78323891, -0.04744974,  0.10242088,
        -1.53788971,  2.64917289,  0.63181571]])

In [183]:
a = pd.DataFrame(log.coef_.T, columns=["Coeff"])
b = pd.DataFrame(X.columns,columns = ["Col"])
c = pd.concat([b,a],axis=1)
c = c.sort_values("Coeff",ascending=False)
col = c["Col"].values[:5]
col

array(['Total_Trans_Ct', 'Total_Revolving_Bal',
       'Total_Relationship_Count', 'Total_Ct_Chng_Q4_Q1', 'Gender'],
      dtype=object)

In [184]:
X_train = X_train[col]
X_test = X_test[col]

In [185]:
log.fit(X_train,y_train)
new_preds = log.predict(X_test)

accuracy_score(y_test,new_preds)

0.8887792036854228

In [186]:
pd.crosstab(y_test,new_preds)

col_0             0     1
Attrition_Flag           
0               223   273
1                65  2478

# With Different Thresholds

In [187]:
# Define the Threshold Function
def predict_threshold(model,X_test,threshold):
    return np.where(np.round(model.predict_proba(X_test)[:,0],3)>= threshold, 0,1)

In [188]:
for i in np.arange(0.1,1,0.1):
    y_pred = predict_threshold(log,X_test,i)
    print("Threshold value:",i)
    print("Confusion Matrix: ")
    print(confusion_matrix(y_test,y_pred))
    print("Accuracy Score",accuracy_score(y_test,y_pred),"\n")
    print()

Threshold value: 0.1
Confusion Matrix: 
[[ 414   82]
 [ 719 1824]]
Accuracy Score 0.736426456071076 


Threshold value: 0.2
Confusion Matrix: 
[[ 363  133]
 [ 371 2172]]
Accuracy Score 0.8341559723593287 


Threshold value: 0.30000000000000004
Confusion Matrix: 
[[ 322  174]
 [ 209 2334]]
Accuracy Score 0.8739717012175058 


Threshold value: 0.4
Confusion Matrix: 
[[ 268  228]
 [ 124 2419]]
Accuracy Score 0.8841724251398486 


Threshold value: 0.5
Confusion Matrix: 
[[ 223  273]
 [  65 2478]]
Accuracy Score 0.8887792036854228 


Threshold value: 0.6
Confusion Matrix: 
[[ 189  307]
 [  31 2512]]
Accuracy Score 0.8887792036854228 


Threshold value: 0.7000000000000001
Confusion Matrix: 
[[ 143  353]
 [  15 2528]]
Accuracy Score 0.8789075353734781 


Threshold value: 0.8
Confusion Matrix: 
[[  92  404]
 [   6 2537]]
Accuracy Score 0.8650871997367555 


Threshold value: 0.9
Confusion Matrix: 
[[  32  464]
 [   1 2542]]
Accuracy Score 0.8469891411648569 


